spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    format_sql: true
  zipkin:
    base-url: http://127.0.0.1:9411
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: address.log