prop:
  type: dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    format_sql: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: student.log

#open feign without eureka
#address:
#  service:
#    url: http://localhost:8081/api/address

resilience4j:
  circuitbreaker:
    instances:
      addressService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5
        allowHealthIndicatorToFail: true
        registerHealthIndicator: true

# actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# current states in the actuator
# closeState = UP, openState = DOWN & haflOpenState = UNKNOWN
